# Generated by Django 2.2.1 on 2019-05-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('parentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp.Classification')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('price', models.CharField(max_length=30, verbose_name='产品价格')),
                ('img', models.FileField(upload_to='', verbose_name='产品图片')),
                ('introduce', models.TextField(verbose_name='产品简介')),
                ('brand', models.CharField(max_length=30, verbose_name='产品品牌')),
                ('size', models.CharField(max_length=30, verbose_name='产品尺寸')),
                ('color', models.CharField(max_length=30, verbose_name='产品颜色')),
                ('material', models.CharField(max_length=30, verbose_name='产品材料')),
                ('inventory', models.IntegerField(verbose_name='库存')),
                ('number', models.IntegerField(default=0, verbose_name='已卖出数量')),
                ('classfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp.Classification')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类型名字')),
                ('product', models.ManyToManyField(to='lamp.Product')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='产品数量')),
                ('product', models.ManyToManyField(to='lamp.Product')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='性名')),
                ('email', models.EmailField(max_length=30, verbose_name='账户邮箱')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('gender', models.CharField(max_length=30, verbose_name='性别')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('activation', models.CharField(default=0, max_length=30)),
                ('shoppingcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp.ShoppingCart')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
    ]
