# Generated by Django 2.2.1 on 2019-05-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a10',
        ),
        migrations.DeleteModel(
            name='a11',
        ),
        migrations.DeleteModel(
            name='a12',
        ),
        migrations.DeleteModel(
            name='a13',
        ),
        migrations.DeleteModel(
            name='a6',
        ),
        migrations.DeleteModel(
            name='a7',
        ),
        migrations.DeleteModel(
            name='a8',
        ),
        migrations.DeleteModel(
            name='a9',
        ),
    ]
