# Generated by Django 2.2.1 on 2019-05-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='parentClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lamp.Classification'),
        ),
    ]
